[tools.rust]
version = "latest"
components = "cargo,rustc,rust-std,rustfmt,clippy"


# [tasks.example_pr]
# run = "cargo run -- bitbucket"
# env = { BB_REPO_SLUG = "your_repo_slug" }

# [tasks.example_pr_find]
# run = "cargo run -- bitbucket find "
# env = { BB_REPO_SLUG = "your_repo_slug" }
